# // Secret 생성
apiVersion: v1
kind: Secret

metadata:
  name: REMOVED-secrets
  # // namespace 추가
  namespace: qKet-prod

type: Opaque


stringData:
  # // RDS(MySQL) 사용자 계정
  DB_USERNAME: REMOVED
  # // RDS(MySQL) 비밀번호
  DB_PASSWORD: REMOVED


  # =================================
  # 프로젝트 Kubernetes 리소스 이름 교체
  # =================================
  # secret : REMOVED-secrets
  # configmap : REMOVED-config
  # backend : REMOVED-backend
  # backend-service : REMOVED-backend-service
  # frontend : REMOVED-frontend
  # frontend-service : REMOVED-frontend-service
  # ingress : REMOVED-alb-ingress