apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-backend
  template:
    metadata:
      labels:
        app: account-backend
    spec:
      containers:
        - name: account-backend
          image: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/team5/ecr/qket:backend-7.3.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_PASSWORD

            - name: SPRING_DATA_REDIS_HOST
              value: redis

            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: account-backend-service
spec:
  type: ClusterIP
  selector:
    app: account-backend
  ports:
    - port: 80
      targetPort: 8080