apiVersion: apps/v1
kind: Deployment
metadata:
  name: REMOVED-frontend

spec:
  revisionHistoryLimit: 2
  replicas: 1

  selector:
    matchLabels:
      app: REMOVED-frontend

  template:
    metadata:
      labels:
        app: REMOVED-frontend

    spec:
      containers:
        - name: REMOVED-frontend
          image: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/team5/ecr/REMOVED:frontend-7.1
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"

          env:
            - name: BACKEND_URL
              value: "http://account-backend-service"

---
apiVersion: v1
kind: Service
metadata:
  name: REMOVED-frontend-service

spec:
  type: ClusterIP

  ports:
    - port: 80
      targetPort: 3000

  selector:
    app: REMOVED-frontend