apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-alb-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:727646470302:certificate/a9789e71-7453-43d9-b0db-ad2ac973f4c0

    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'

spec:
  ingressClassName: alb
  rules:
    - host: app.jun979.click
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: account-backend-service
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: REMOVED-frontend-service
                port:
                  number: 80