apiVersion: v1
kind: Namespace
metadata:
  name: qKet-prod
  labels:
    name: qKet-prod # NetworkPolicy namespaceSelector에서 이 label로 참조됨
---
apiVersion: v1
kind: Namespace
metadata:
  name: qKet-prod
  labels:
    name: qKet-prod
