apiVersion: v1
kind: Namespace
metadata:
  name: qket-prod
  labels:
    name: qket-prod # NetworkPolicy namespaceSelectr
---
apiVersion: v1
kind: Namespace
metadata:
  name: qket-dev
  labels:
    name: qket-dev
