USE REMOVED;

-- =========================
-- Qket 테스트 데이터
-- =========================

-- ROLES
INSERT INTO ROLES (role_name) VALUES
  ('USER'),
  ('MANAGER'),
  ('ADMIN');

-- PERFORMANCES
INSERT INTO PERFORMANCES (p_title, p_location, poster_url) VALUES
  ('아이유 콘서트 - The Golden Hour', '서울 올림픽공원 체조경기장', 'https://example.com/poster/iu.jpg'),
  ('BTS 월드투어 - Seoul', '서울 잠실 종합운동장 주경기장', 'https://example.com/poster/bts.jpg'),
  ('재즈 나잇 - Blue Note Seoul', '부산 벡스코 오디토리움', 'https://example.com/poster/jazznight.jpg');

-- USERS password : test1234
INSERT INTO USERS (user_id, user_nm, pwd, user_email, role_id, user_status) VALUES
  ('REMOVED01', '관리자01', '$2b$10$hWBKmcDTCeEpTSo69AszSOq83qcpV.y7HJwWtweymXyxLmL7kD4Am', 'REMOVED01@REMOVED.com', 3, 'ACTIVE'),
  ('manager01', '매니저01', '$2b$10$hWBKmcDTCeEpTSo69AszSOq83qcpV.y7HJwWtweymXyxLmL7kD4Am', 'manager01@REMOVED.com', 2, 'ACTIVE'),
  ('testuser01', '테스트유저01', '$2b$10$hWBKmcDTCeEpTSo69AszSOq83qcpV.y7HJwWtweymXyxLmL7kD4Am', 'testuser01@REMOVED.com', 1, 'ACTIVE'),
  ('testuser02', '테스트유저02', '$2b$10$hWBKmcDTCeEpTSo69AszSOq83qcpV.y7HJwWtweymXyxLmL7kD4Am', 'testuser02@REMOVED.com', 1, 'ACTIVE'),
  ('testuser03', '테스트유저03', '$2b$10$hWBKmcDTCeEpTSo69AszSOq83qcpV.y7HJwWtweymXyxLmL7kD4Am', 'testuser03@REMOVED.com', 1, 'ACTIVE'),
  ('testuser04', '테스트유저04', '$2b$10$hWBKmcDTCeEpTSo69AszSOq83qcpV.y7HJwWtweymXyxLmL7kD4Am', 'testuser04@REMOVED.com', 1, 'ACTIVE'),
  ('testuser05', '테스트유저05', '$2b$10$hWBKmcDTCeEpTSo69AszSOq83qcpV.y7HJwWtweymXyxLmL7kD4Am', 'testuser05@REMOVED.com', 1, 'ACTIVE'),
  ('testuser06', '테스트유저06', '$2b$10$hWBKmcDTCeEpTSo69AszSOq83qcpV.y7HJwWtweymXyxLmL7kD4Am', 'testuser06@REMOVED.com', 1, 'SUSPENDED');

-- PERFORMANCE_ROUND
INSERT INTO PERFORMANCE_ROUND (performance_id, round_time, round_status) VALUES
  (1, '2026-08-15 19:00:00', 'SCHEDULED'),
  (1, '2026-08-16 17:00:00', 'SCHEDULED'),
  (2, '2026-09-01 19:30:00', 'SCHEDULED'),
  (2, '2026-09-02 19:30:00', 'SCHEDULED'),
  (3, '2026-08-20 20:00:00', 'SCHEDULED'),
  (3, '2026-08-21 20:00:00', 'CLOSED');

-- SEATS (라운드별 5행 x 6열 = 30석, VIP/R/S 등급)
INSERT INTO SEATS (round_id, seat_row, seat_colume, grade, status) VALUES
  (1, 'A', '1', 'VIP', 'reserved'),
  (1, 'A', '2', 'VIP', 'reserved'),
  (1, 'A', '3', 'VIP', 'available'),
  (1, 'A', '4', 'VIP', 'available'),
  (1, 'A', '5', 'VIP', 'available'),
  (1, 'A', '6', 'VIP', 'available'),
  (1, 'B', '1', 'VIP', 'available'),
  (1, 'B', '2', 'VIP', 'available'),
  (1, 'B', '3', 'VIP', 'available'),
  (1, 'B', '4', 'VIP', 'available'),
  (1, 'B', '5', 'VIP', 'available'),
  (1, 'B', '6', 'VIP', 'available'),
  (1, 'C', '1', 'R', 'available'),
  (1, 'C', '2', 'R', 'available'),
  (1, 'C', '3', 'R', 'available'),
  (1, 'C', '4', 'R', 'available'),
  (1, 'C', '5', 'R', 'available'),
  (1, 'C', '6', 'R', 'available'),
  (1, 'D', '1', 'R', 'available'),
  (1, 'D', '2', 'R', 'available'),
  (1, 'D', '3', 'R', 'available'),
  (1, 'D', '4', 'R', 'available'),
  (1, 'D', '5', 'R', 'available'),
  (1, 'D', '6', 'R', 'available'),
  (1, 'E', '1', 'S', 'available'),
  (1, 'E', '2', 'S', 'available'),
  (1, 'E', '3', 'S', 'available'),
  (1, 'E', '4', 'S', 'available'),
  (1, 'E', '5', 'S', 'available'),
  (1, 'E', '6', 'S', 'available'),
  (2, 'A', '1', 'VIP', 'available'),
  (2, 'A', '2', 'VIP', 'available'),
  (2, 'A', '3', 'VIP', 'available'),
  (2, 'A', '4', 'VIP', 'available'),
  (2, 'A', '5', 'VIP', 'available'),
  (2, 'A', '6', 'VIP', 'available'),
  (2, 'B', '1', 'VIP', 'available'),
  (2, 'B', '2', 'VIP', 'available'),
  (2, 'B', '3', 'VIP', 'available'),
  (2, 'B', '4', 'VIP', 'available'),
  (2, 'B', '5', 'VIP', 'available'),
  (2, 'B', '6', 'VIP', 'available'),
  (2, 'C', '1', 'R', 'available'),
  (2, 'C', '2', 'R', 'available'),
  (2, 'C', '3', 'R', 'available'),
  (2, 'C', '4', 'R', 'available'),
  (2, 'C', '5', 'R', 'available'),
  (2, 'C', '6', 'R', 'available'),
  (2, 'D', '1', 'R', 'available'),
  (2, 'D', '2', 'R', 'available'),
  (2, 'D', '3', 'R', 'available'),
  (2, 'D', '4', 'R', 'available'),
  (2, 'D', '5', 'R', 'available'),
  (2, 'D', '6', 'R', 'available'),
  (2, 'E', '1', 'S', 'available'),
  (2, 'E', '2', 'S', 'available'),
  (2, 'E', '3', 'S', 'available'),
  (2, 'E', '4', 'S', 'available'),
  (2, 'E', '5', 'S', 'available'),
  (2, 'E', '6', 'S', 'available'),
  (3, 'A', '1', 'VIP', 'reserved'),
  (3, 'A', '2', 'VIP', 'reserved'),
  (3, 'A', '3', 'VIP', 'available'),
  (3, 'A', '4', 'VIP', 'available'),
  (3, 'A', '5', 'VIP', 'available'),
  (3, 'A', '6', 'VIP', 'available'),
  (3, 'B', '1', 'VIP', 'available'),
  (3, 'B', '2', 'VIP', 'available'),
  (3, 'B', '3', 'VIP', 'available'),
  (3, 'B', '4', 'VIP', 'available'),
  (3, 'B', '5', 'VIP', 'available'),
  (3, 'B', '6', 'VIP', 'available'),
  (3, 'C', '1', 'R', 'available'),
  (3, 'C', '2', 'R', 'available'),
  (3, 'C', '3', 'R', 'available'),
  (3, 'C', '4', 'R', 'available'),
  (3, 'C', '5', 'R', 'available'),
  (3, 'C', '6', 'R', 'available'),
  (3, 'D', '1', 'R', 'available'),
  (3, 'D', '2', 'R', 'available'),
  (3, 'D', '3', 'R', 'available'),
  (3, 'D', '4', 'R', 'available'),
  (3, 'D', '5', 'R', 'available'),
  (3, 'D', '6', 'R', 'available'),
  (3, 'E', '1', 'S', 'available'),
  (3, 'E', '2', 'S', 'available'),
  (3, 'E', '3', 'S', 'available'),
  (3, 'E', '4', 'S', 'available'),
  (3, 'E', '5', 'S', 'available'),
  (3, 'E', '6', 'S', 'available'),
  (4, 'A', '1', 'VIP', 'available'),
  (4, 'A', '2', 'VIP', 'available'),
  (4, 'A', '3', 'VIP', 'available'),
  (4, 'A', '4', 'VIP', 'available'),
  (4, 'A', '5', 'VIP', 'available'),
  (4, 'A', '6', 'VIP', 'available'),
  (4, 'B', '1', 'VIP', 'available'),
  (4, 'B', '2', 'VIP', 'available'),
  (4, 'B', '3', 'VIP', 'available'),
  (4, 'B', '4', 'VIP', 'available'),
  (4, 'B', '5', 'VIP', 'available'),
  (4, 'B', '6', 'VIP', 'available'),
  (4, 'C', '1', 'R', 'available'),
  (4, 'C', '2', 'R', 'available'),
  (4, 'C', '3', 'R', 'available'),
  (4, 'C', '4', 'R', 'available'),
  (4, 'C', '5', 'R', 'available'),
  (4, 'C', '6', 'R', 'available'),
  (4, 'D', '1', 'R', 'available'),
  (4, 'D', '2', 'R', 'available'),
  (4, 'D', '3', 'R', 'available'),
  (4, 'D', '4', 'R', 'available'),
  (4, 'D', '5', 'R', 'available'),
  (4, 'D', '6', 'R', 'available'),
  (4, 'E', '1', 'S', 'available'),
  (4, 'E', '2', 'S', 'available'),
  (4, 'E', '3', 'S', 'available'),
  (4, 'E', '4', 'S', 'available'),
  (4, 'E', '5', 'S', 'available'),
  (4, 'E', '6', 'S', 'available'),
  (5, 'A', '1', 'VIP', 'reserved'),
  (5, 'A', '2', 'VIP', 'reserved'),
  (5, 'A', '3', 'VIP', 'available'),
  (5, 'A', '4', 'VIP', 'available'),
  (5, 'A', '5', 'VIP', 'available'),
  (5, 'A', '6', 'VIP', 'available'),
  (5, 'B', '1', 'VIP', 'available'),
  (5, 'B', '2', 'VIP', 'available'),
  (5, 'B', '3', 'VIP', 'available'),
  (5, 'B', '4', 'VIP', 'available'),
  (5, 'B', '5', 'VIP', 'available'),
  (5, 'B', '6', 'VIP', 'available'),
  (5, 'C', '1', 'R', 'available'),
  (5, 'C', '2', 'R', 'available'),
  (5, 'C', '3', 'R', 'available'),
  (5, 'C', '4', 'R', 'available'),
  (5, 'C', '5', 'R', 'available'),
  (5, 'C', '6', 'R', 'available'),
  (5, 'D', '1', 'R', 'available'),
  (5, 'D', '2', 'R', 'available'),
  (5, 'D', '3', 'R', 'available'),
  (5, 'D', '4', 'R', 'available'),
  (5, 'D', '5', 'R', 'available'),
  (5, 'D', '6', 'R', 'available'),
  (5, 'E', '1', 'S', 'available'),
  (5, 'E', '2', 'S', 'available'),
  (5, 'E', '3', 'S', 'available'),
  (5, 'E', '4', 'S', 'available'),
  (5, 'E', '5', 'S', 'available'),
  (5, 'E', '6', 'S', 'available'),
  (6, 'A', '1', 'VIP', 'available'),
  (6, 'A', '2', 'VIP', 'available'),
  (6, 'A', '3', 'VIP', 'available'),
  (6, 'A', '4', 'VIP', 'available'),
  (6, 'A', '5', 'VIP', 'available'),
  (6, 'A', '6', 'VIP', 'available'),
  (6, 'B', '1', 'VIP', 'available'),
  (6, 'B', '2', 'VIP', 'available'),
  (6, 'B', '3', 'VIP', 'available'),
  (6, 'B', '4', 'VIP', 'available'),
  (6, 'B', '5', 'VIP', 'available'),
  (6, 'B', '6', 'VIP', 'available'),
  (6, 'C', '1', 'R', 'available'),
  (6, 'C', '2', 'R', 'available'),
  (6, 'C', '3', 'R', 'available'),
  (6, 'C', '4', 'R', 'available'),
  (6, 'C', '5', 'R', 'available'),
  (6, 'C', '6', 'R', 'available'),
  (6, 'D', '1', 'R', 'available'),
  (6, 'D', '2', 'R', 'available'),
  (6, 'D', '3', 'R', 'available'),
  (6, 'D', '4', 'R', 'available'),
  (6, 'D', '5', 'R', 'available'),
  (6, 'D', '6', 'R', 'available'),
  (6, 'E', '1', 'S', 'available'),
  (6, 'E', '2', 'S', 'available'),
  (6, 'E', '3', 'S', 'available'),
  (6, 'E', '4', 'S', 'available'),
  (6, 'E', '5', 'S', 'available'),
  (6, 'E', '6', 'S', 'available');

-- RESERVATIONS (위에서 status='reserved'로 표시한 좌석과 매칭)
INSERT INTO RESERVATIONS (user_id, seat_id, round_id, reserved_status) VALUES
  ('testuser01', 1, 1, 'reserved'),
  ('testuser02', 2, 1, 'reserved'),
  ('testuser03', 61, 3, 'reserved'),
  ('testuser04', 62, 3, 'reserved'),
  ('testuser05', 121, 5, 'reserved'),
  ('testuser01', 122, 5, 'reserved');

-- 검증용 조회f
/*
SELECT COUNT(*) AS role_count FROM ROLES;
SELECT COUNT(*) AS performance_count FROM PERFORMANCES;
SELECT COUNT(*) AS user_count FROM USERS;
SELECT COUNT(*) AS round_count FROM PERFORMANCE_ROUND;
SELECT COUNT(*) AS seat_count FROM SEATS;
SELECT COUNT(*) AS reservation_count FROM RESERVATIONS;
*/