name: Secret Scan

on:
  # 처음 작동 확인용
  push:
    branches:
      - yunjun

  # 팀 공용 기능
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:
  gitleaks:
    name: Detect leaked secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}